version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: simpleform-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simpleform-backend
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      MongoDbSettings__ConnectionString: mongodb://mongo:27017
      MongoDbSettings__DatabaseName: SimpleFormDb
      MongoDbSettings__CollectionName: Submissions
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simpleform-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data:
