apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: simpleform
data:
  ASPNETCORE_URLS: http://+:8080
  MongoDbSettings__ConnectionString: mongodb://mongo:27017
  MongoDbSettings__DatabaseName: SimpleFormDb
  MongoDbSettings__CollectionName: Submissions
